# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleID', models.AutoField(primary_key=True, serialize=False)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('contentURL', models.URLField()),
                ('articleTitle', models.CharField(max_length=30)),
                ('label', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': '文章列表',
            },
        ),
        migrations.CreateModel(
            name='ArticleCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('articleCommentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.CharField(max_length=466)),
                ('commentTime', models.DateTimeField()),
                ('commentArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
            options={
                'verbose_name_plural': '文章评论表',
            },
        ),
        migrations.CreateModel(
            name='ArticleRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('dynamicID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '动态列表',
            },
        ),
        migrations.CreateModel(
            name='DynamicComment',
            fields=[
                ('dynamicCommentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.CharField(max_length=466)),
                ('commentTime', models.DateTimeField()),
                ('commentDynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
            options={
                'verbose_name_plural': '动态评论表',
            },
        ),
        migrations.CreateModel(
            name='DynamicThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeDynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Dynamic')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('ideaID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createDate', models.DateTimeField()),
                ('label', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': '想法列表',
            },
        ),
        migrations.CreateModel(
            name='IdeaCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionIdea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Idea')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendIdea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Idea')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeIdea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Idea')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personID', models.AutoField(primary_key=True, serialize=False)),
                ('personName', models.CharField(max_length=30)),
                ('personPassword', models.CharField(max_length=128)),
                ('personMobile', models.CharField(max_length=20)),
                ('personEmail', models.EmailField(max_length=50)),
                ('personImage', models.CharField(max_length=100)),
                ('personInfo', models.CharField(max_length=100, null=True)),
                ('personSex', models.CharField(max_length=5, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('enrollDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '用户列表',
            },
        ),
        migrations.CreateModel(
            name='PersonFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee_person', to='index.Person')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_person', to='index.Person')),
            ],
            options={
                'verbose_name_plural': '关注列表',
            },
        ),
        migrations.AddField(
            model_name='ideathumbup',
            name='likeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='idearecommend',
            name='recommendrecommendUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='ideacollection',
            name='collectionUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='idea',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='dynamicthumbup',
            name='likeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='dynamiccomment',
            name='commentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='articlethumbup',
            name='likeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='articlerecommend',
            name='recommendtUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='commentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='articlecollection',
            name='collectionUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='article',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
    ]
