# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-05 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecollection',
            options={'verbose_name_plural': '\u6587\u7ae0\u6536\u85cf\u8868'},
        ),
        migrations.AlterModelOptions(
            name='articlerecommend',
            options={'verbose_name_plural': '\u6587\u7ae0\u63a8\u8350\u8868'},
        ),
        migrations.AlterModelOptions(
            name='articlethumbup',
            options={'verbose_name_plural': '\u6587\u7ae0\u70b9\u8d5e\u8868'},
        ),
        migrations.AlterModelOptions(
            name='dynamicthumbup',
            options={'verbose_name_plural': '\u52a8\u6001\u70b9\u8d5e\u8868'},
        ),
        migrations.AlterModelOptions(
            name='ideacollection',
            options={'verbose_name_plural': '\u60f3\u6cd5\u6536\u85cf\u8868'},
        ),
        migrations.AlterModelOptions(
            name='idearecommend',
            options={'verbose_name_plural': '\u60f3\u6cd5\u63a8\u8350\u8868'},
        ),
        migrations.AlterModelOptions(
            name='ideathumbup',
            options={'verbose_name_plural': '\u60f3\u6cd5\u70b9\u8d5e\u8868'},
        ),
    ]
