# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleID', models.AutoField(primary_key=True, serialize=False)),
                ('createData', models.DateField(auto_now_add=True)),
                ('contentURL', models.URLField()),
                ('articleTitle', models.CharField(max_length=30)),
                ('label', models.BinaryField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '\u6587\u7ae0\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ArticleCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
            options={
                'verbose_name_plural': '\u6587\u7ae0\u6536\u85cf\u8868',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('articleCommentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.CharField(max_length=466)),
                ('commentTime', models.DateField()),
                ('commentArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
            options={
                'verbose_name_plural': '\u6587\u7ae0\u8bc4\u8bba\u8868',
            },
        ),
        migrations.CreateModel(
            name='ArticleRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
            options={
                'verbose_name_plural': '\u6587\u7ae0\u63a8\u8350\u8868',
            },
        ),
        migrations.CreateModel(
            name='ArticleThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
            options={
                'verbose_name_plural': '\u6587\u7ae0\u70b9\u8d5e\u8868',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('dynamicID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createData', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '\u52a8\u6001\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='DynamicComment',
            fields=[
                ('dynamicCommentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.CharField(max_length=466)),
                ('commentTime', models.DateField()),
                ('commentDynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article')),
            ],
            options={
                'verbose_name_plural': '\u52a8\u6001\u8bc4\u8bba\u8868',
            },
        ),
        migrations.CreateModel(
            name='DynamicThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeDynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Dynamic')),
            ],
            options={
                'verbose_name_plural': '\u52a8\u6001\u70b9\u8d5e\u8868',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('ideaID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createData', models.DateField()),
                ('label', models.BinaryField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '\u60f3\u6cd5\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='IdeaCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionIdea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Idea')),
            ],
            options={
                'verbose_name_plural': '\u60f3\u6cd5\u6536\u85cf\u8868',
            },
        ),
        migrations.CreateModel(
            name='IdeaRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendIdea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Idea')),
            ],
            options={
                'verbose_name_plural': '\u60f3\u6cd5\u63a8\u8350\u8868',
            },
        ),
        migrations.CreateModel(
            name='IdeaThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeIdea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Idea')),
            ],
            options={
                'verbose_name_plural': '\u60f3\u6cd5\u70b9\u8d5e\u8868',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personID', models.AutoField(primary_key=True, serialize=False)),
                ('personName', models.CharField(max_length=30)),
                ('personPassword', models.CharField(max_length=20)),
                ('personMobile', models.CharField(max_length=20)),
                ('personEmail', models.EmailField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('enrollDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='PersonFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee_person', to='index.Person')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_person', to='index.Person')),
            ],
            options={
                'verbose_name_plural': '\u5173\u6ce8\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='ideathumbup',
            name='likeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='idearecommend',
            name='recommendrecommendUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='ideacollection',
            name='collectionUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='idea',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='dynamicthumbup',
            name='likeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='dynamiccomment',
            name='commentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='articlethumbup',
            name='likeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='articlerecommend',
            name='recommendtUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='commentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='articlecollection',
            name='collectionUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
        migrations.AddField(
            model_name='article',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Person'),
        ),
    ]
