# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createData',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='commentTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='createData',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dynamiccomment',
            name='commentTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='createData',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='enrollDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
